server:
  port: 8080
  tomcat:
    apr:
      enabled: false
  servlet:
    init-parameters:
      dispatcherServletRegistration:
        loadOnStartup: 1
spring:
  boot:
    condition-evaluation-report:
      enabled: false
  application:
    name: spring-native-demo
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  resource:
    static-locations: classpath:/static/
  # Spring Native
  aot:
    enabled: true
  native:
    remove-yaml-support: true

#MyBatis-Plus配置
mybatis-plus:
  type-aliases-package: com.leosam.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  file:
    name: ./logs/demo.log
  level:
    root: INFO
    org.springframework: INFO
    com.leosam: debug
    sun.rmi: WARN
    java.rmi: WARN
